[package]
name = "semilattice-database"
version = "0.5.2"
edition = "2021"

description = "This is a new database engine under development.A database is not a tree."

repository = "https://github.com/OdenShirataki/semilattice-database"

keywords = ["database","library"]
license = "MIT/Apache-2.0"

[dependencies]
versatile-data={ path="../versatile-data" , version="0.28" }
idx_binary={ path="../idx_binary" , version="0.3" }
