[workspace]
resolver = "2"
members = ["semilattice-database", "semilattice-database-session"]

[workspace.dependencies]
serde = "1.0.193"
futures = "0.3.29"
async-recursion = "1.0.5"
hashbrown = "0.14.3"

semilattice-database = { version = "0", path = "semilattice-database" }
