[package]
name = "semilattice-database"
version = "0.1.0"
edition = "2021"

description = "A library for databases that has convenient datasets that group together commonly used fields and gives you the flexibility to create your own fields."

repository = "https://github.com/OdenShirataki/semilattice-database"

keywords = ["database","library"]
license = "MIT/Apache-2.0"

[dependencies]
versatile-data={ path="../versatile-data" , version="0.22" }
