[package]
name = "semilattice-database"
version = "0.20.2"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Data is connected by a directed graph, and each node has an arbitrarily defined key-value.A database is not a tree."

repository = "https://github.com/OdenShirataki/semilattice-database"

keywords = ["database","library"]
categories = ["database","database-implementations"]
license = "MIT/Apache-2.0"

[dependencies]
chrono="0.4"

versatile-data={path="../versatile-data" , version="0.41"}
idx_binary={path="../idx_binary" , version="0.4"}
file_mmap="0.4"
