[workspace]
resolver = "2"
members = [
    "semilattice-database",
    "semilattice-database-session",
]

[workspace.dependencies]
serde = "1"
futures = "0.3"
async-recursion = "1.0"
hashbrown = "0.14.0"

semilattice-database = "0"
