[package]
name = "semilattice-database"
version = "0.7.2"
edition = "2021"

description = "Data is connected by a directed graph, and each node has an arbitrarily defined key-value..A database is not a tree."

repository = "https://github.com/OdenShirataki/semilattice-database"

keywords = ["database","library"]
categories = ["database","database-implementations"]
license = "MIT/Apache-2.0"

[dependencies]
versatile-data="0.33"
idx_binary="0.3"
file_mmap="0.4"
