[package]
name = "semilattice-database"
version = "0.7.1"
edition = "2021"

description = "This is a new database engine under development.A database is not a tree."

repository = "https://github.com/OdenShirataki/semilattice-database"

keywords = ["database","library"]
categories = ["database","database-implementations"]
license = "MIT/Apache-2.0"

[dependencies]
versatile-data="0.33"
idx_binary="0.3"
file_mmap="0.4"
